const lessonTitle = "弟弟的来信";

const lessonData = [
    // 正文第 1 段
    ["师范", "shī fàn", "normal school / teacher's college", "maktab perguruan"],
    ["毕业", "bì yè", "graduate", "graduat"],
    ["的", "de", "particle", "yang"],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["高高兴兴", "gāo gāo xìng xìng", "happily", "dengan gembira"],
    ["去", "qù", "go to", "pergi ke"],
    ["清泉乡", "qīng quán xiāng", "Qingquan Village", "Kampung Qingquan"],
    ["小学", "xiǎo xué", "primary school", "sekolah rendah"],
    ["报到", "bào dào", "report for duty", "melapor diri"],
    ["，", "", "", ""],
    ["以为", "yǐ wéi", "thought / assumed", "menyangka / berfikir"],
    ["那", "nà", "that", "itu"],
    ["是", "shì", "was", "adalah"],
    ["个", "gè", "measure word", "sebuah"],
    ["好", "hǎo", "good", "bagus / baik"],
    ["地方", "dì fang", "place", "tempat"],
    ["。", "", "", ""],
    ["两天", "liǎng tiān", "two days", "dua hari"],
    ["后", "hòu", "after", "selepas"],
    ["回来", "huí lái", "came back", "kembali / pulang"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["垂头丧气", "chuí tóu sàng qì", "dejected / crestfallen", "hampa / kecewa / tunduk layu"],
    ["地", "de", "particle", "dengan"],
    ["闷", "mēn", "shut oneself up / brooding", "memperam diri / terperap"],
    ["在", "zài", "in", "di"],
    ["家里", "jiā lǐ", "home", "dalam rumah"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["问", "wèn", "asked", "bertanya"],
    ["了", "le", "particle", ""],
    ["许多", "xǔ duō", "many", "banyak"],
    ["遍", "biàn", "times", "kali"],
    ["，", "", "", ""],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["才", "cái", "only then", "baru"],
    ["闷出", "mēn chū", "muttered out / squeezed out", "mengeluarkan kata / meluahkan"],
    ["一句话", "yí jù huà", "a sentence", "sepatah kata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["不是", "bú shì", "is not", "bukan"],
    ["人", "rén", "human / people", "manusia / orang"],
    ["待", "dāi", "stay / live", "tinggal / duduk"],
    ["的", "de", "particle", "yang"],
    ["地方", "dì fang", "place", "tempat"],
    ["。”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 第 2 段

    ["一天", "yì tiān", "one day", "satu hari"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["又", "yòu", "again", "lagi / sekali lagi"],
    ["走", "zǒu", "left / went", "pergi / bertolak"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["是", "shì", "was", "adalah"],
    ["被", "bèi", "by (passive)", "oleh / di-"],
    ["爹", "diē", "dad / father", "ayah"],
    ["拿着", "ná zhe", "holding", "memegang"],
    ["木棒", "mù bàng", "wooden stick / club", "kayu pemukul / kayu rod"],
    ["撵", "niǎn", "drive out / chase out", "menghalau / mengejar"],
    ["回去", "huí qù", "back", "pulang / balik"],
    ["的", "de", "particle", ""],
    ["。", "", "", ""],
    ["爹", "diē", "dad", "ayah"],
    ["一直", "yì zhí", "kept / constantly", "sentiasa / asyik"],
    ["在", "zài", "verb particle (-ing)", "sedang"],
    ["骂", "mà", "scolding / swearing", "memarahi / memaki"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["咋", "zǎ", "how / what", "kenapa / mengapa"],
    ["？", "", "", ""],
    ["不是", "bú shì", "not", "bukan"],
    ["人", "rén", "human", "manusia"],
    ["待", "dāi", "stay", "tinggal"],
    ["的", "de", "particle", "yang"],
    ["地方", "dì fang", "place", "tempat"],
    ["？", "", "", ""],
    ["只要", "zhǐ yào", "as long as", "asalkan"],
    ["有人", "yǒu rén", "there are people", "ada orang"],
    ["住", "zhù", "live / reside", "tinggal / mendiami"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "is / exactly is", "ialah / sememangnya"],
    ["人", "rén", "human", "manusia"],
    ["待", "dāi", "stay", "tinggal"],
    ["的", "de", "particle", "yang"],
    ["地方", "dì fang", "place", "tempat"],
    ["！", "", "", ""],
    ["你", "nǐ", "you", "kamu / kau"],
    ["个", "gè", "measure word", "si"],
    ["兔崽子", "tù zǎi zi", "you little brat / bastard", "anak bertuah / kurang ajar"],
    ["，", "", "", ""],
    ["要", "yào", "if / want", "kalau / jika"],
    ["再", "zài", "again", "lagi"],
    ["随便", "suí biàn", "carelessly / casually", "sesuka hati / sebarangan"],
    ["跑", "pǎo", "run / sneak", "lari / menyelinap"],
    ["回来", "huí lái", "back here", "pulang ke sini"],
    ["，", "", "", ""],
    ["瞧", "qiáo", "look / see", "lihat / tengok"],
    ["我", "wǒ", "I", "aku / saya"],
    ["打断", "dǎ duàn", "break", "patahkan"],
    ["你的", "nǐ de", "your", "kamu punya"],
    ["腿", "tuǐ", "leg", "kaki"],
    ["！”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 第 3 段

    ["于是", "yú shì", "so / therefore", "maka / oleh itu"],
    ["我就", "wǒ jiù", "I then", "saya pun"],
    ["不能", "bù néng", "cannot", "tidak dapat"],
    ["再", "zài", "again", "lagi"],
    ["瞧见", "qiáo jiàn", "see / catch sight of", "melihat / nampak"],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["的", "de", "of", "punya"],
    ["人", "rén", "person / shadow", "kelibat / diri"],
    ["，", "", "", ""],
    ["只能", "zhǐ néng", "could only", "hanya boleh"],
    ["隔上", "gé shàng", "after / at intervals of", "selang / selepas tempoh"],
    ["一段时间", "yí duàn shí jiān", "a period of time", "suatu masa"],
    ["天外来客", "tiān wài lái kè", "visitor from outer space", "tetamu dari luar angkasa / makhluk asing"],
    ["似的", "shì de", "like / as if", "seperti / seolah-olah"],
    ["瞧上", "qiáo shàng", "see / read", "melihat / menerima"],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["的", "de", "of", "punya"],
    ["来信", "lái xìn", "incoming letter", "surat yang dihantar"],
    ["。", "", "", ""],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["说", "shuō", "said", "berkata / menulis"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["个", "gè", "measure word", "sebuah"],
    ["兔子不拉屎", "tù zi bù lā shǐ", "godforsaken / desolate (lit. rabbits don't poop)", "tempat jin bertendang / sangat terpencil"],
    ["的", "de", "particle", "yang"],
    ["地方", "dì fang", "place", "tempat"],
    ["，", "", "", ""],
    ["没有", "méi yǒu", "no / without", "tiada"],
    ["电", "diàn", "electricity", "bekalan elektrik"],
    ["，", "", "", ""],
    ["没有", "méi yǒu", "no / without", "tiada"],
    ["水", "shuǐ", "water", "bekalan air"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "jika / sekiranya"],
    ["拍", "pāi", "film / shoot", "merakam / membuat penggambaran"],
    ["鬼子进村", "guǐ zi jìn cūn", "invaders entering the village", "tentera musuh menceroboh kampung"],
    ["的", "de", "particle", "yang"],
    ["电影", "diàn yǐng", "movie", "filem"],
    ["，", "", "", ""],
    ["这里", "zhè lǐ", "here", "sini / di sini"],
    ["最", "zuì", "most", "paling"],
    ["合适", "hé shì", "suitable", "sesuai / sepadan"],
    ["。”", "", "", ""], // 🎯 已完全修复合并
    ["爹", "diē", "dad", "ayah"],
    ["听完", "tīng wán", "after hearing", "setelah mendengar"],
    ["哼", "hēng", "snorted", "mendengus"],
    ["一声", "yì shēng", "once / a sound", "sekali"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["放狗屁", "fàng gǒu pì", "nonsense / bullshit (lit. farting like a dog)", "cakap merapu / karut / omong kosong"],
    ["！”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 第 4 段

    ["后来", "hòu lái", "later on", "kemudian / lama-kelamaan"],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["又", "yòu", "again", "lagi"],
    ["来信", "lái xìn", "wrote a letter", "menghantar surat"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata / menceritakan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["经常", "jīng cháng", "often / frequently", "sering kali / kerap kali"],
    ["能", "néng", "can / able to", "boleh / dapat"],
    ["吃到", "chī dào", "get to eat", "makan"],
    ["乡亲们", "xiāng qīn men", "villagers / folks", "orang-orang kampung / penduduk kampung"],
    ["送来", "sòng lái", "sent over", "hantar ke sini / memberi"],
    ["的", "de", "particle", "yang"],
    ["肉块", "ròu kuài", "meat chunks", "ketulan daging"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["他们的", "tā men de", "their", "mereka punya"],
    ["孩子", "hái zi", "children", "anak-anak"],
    ["认字", "rèn zì", "learn to read / recognize characters", "mengenal huruf / celik huruf"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["那种", "nà zhǒng", "that kind of", "daging jenis itu"],
    ["肉块", "ròu kuài", "meat chunks", "ketulan daging"],
    ["红红的", "hóng hóng de", "reddish", "kemerah-merahan"],
    ["，", "", "", ""],
    ["白白的", "bái bái de", "whitish", "keputih-putihan"],
    ["，", "", "", ""],
    ["很好吃", "hěn hǎo chī", "very delicious", "sangat sedap"],
    ["，", "", "", ""],
    ["吃得", "chī de", "ate (with results)", "makan dengan"],
    ["很多", "hěn duō", "a lot", "banyak"],
    ["，", "", "", ""],
    ["后来", "hòu lái", "later", "kemudian / setelah itu"],
    ["才", "cái", "only then", "baru"],
    ["知道", "zhī dào", "knew / found out", "tahu / mendapat tahu"],
    ["是", "shì", "was", "adalah"],
    ["耗子肉", "hào zi ròu", "rat meat", "daging tikus"],
    ["和", "hé", "and", "dan"],
    ["蛇肉", "shé ròu", "snake meat", "daging ular"],
    ["，", "", "", ""],
    ["又", "yòu", "and then", "lalu"],
    ["全部", "quán bù", "all / completely", "semua sekali"],
    ["呕", "ǒu", "vomited", "muntahkan"],
    ["了", "le", "particle", ""],
    ["。”", "", "", ""], // 🎯 已完全修复合并
    ["我", "wǒ", "I", "saya"],
    ["笑着", "xiào zhe", "smilingly", "sambil tersenyum"],
    ["读完", "dú wán", "finished reading", "habis membaca"],
    ["信", "xìn", "letter", "surat"],
    ["，", "", "", ""],
    ["爹", "diē", "dad", "ayah"],
    ["却", "què", "however", "namun / sebaliknya"],
    ["一脸", "yì liǎn", "a face full of", "mempunyai raut wajah"],
    ["慎重", "shèn zhòng", "solemn / serious", "serius / tegas / teliti"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["肉", "ròu", "meat", "daging"],
    ["我", "wǒ", "I", "aku"],
    ["吃过", "chī guò", "have eaten", "pernah makan"],
    ["，", "", "", ""],
    ["味道", "wèi dào", "taste / flavor", "rasa"],
    ["很好", "hěn hǎo", "very good", "sangat sedap / baik"],
    ["。”", "", "", ""], // 🎯 已完全修复合并
    ["我", "wǒ", "I", "saya"],
    ["问", "wèn", "asked", "bertanya"],
    ["哪一年", "nǎ yì nián", "which year", "tahun mana / bila"],
    ["吃的", "chī de", "ate it", "makan"],
    ["，", "", "", ""],
    ["爹", "diē", "dad", "ayah"],
    ["说", "shuō", "said", "berkata"],
    ["是", "shì", "was", "adalah pada"],
    ["三年灾荒时期", "sān nián zāi huāng shí qī", "Three Years of Great Famine", "Tempoh Tiga Tahun Kebuluran Besar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["再", "zài", "even / further", "kemudian"],
    ["后来", "hòu lái", "later", "selepas itu"],
    ["，", "", "", ""],
    ["收到", "shōu dào", "received", "menerima"],
    ["一个", "yí gè", "a / one", "sebuah"],
    ["包裹", "bāo guǒ", "parcel / package", "bingkisan / bungkusan"],
    ["。", "", "", ""],
    ["打开", "dǎ kāi", "open", "buka"],
    ["一看", "yí kàn", "and took a look", "dan melihat"],
    ["，", "", "", ""],
    ["是", "shì", "was", "adalah"],
    ["一件", "yí jiàn", "a piece of (clothing)", "sehelai"],
    ["毛皮", "máo pí", "fur", "bulu binatang"],
    ["坎肩", "kǎn jiān", "vest / waistcoat", "ves / baju tanpa lengan"],
    ["。", "", "", ""],
    ["爹", "diē", "dad", "ayah"],
    ["摸摸", "mō mō", "touched / stroked", "meraba-raba / menyentuh"],
    ["，", "", "", ""],
    ["惊呼", "jīng hū", "exclaimed in surprise", "berseru terkejut"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["黄鼠狼皮", "huáng shǔ láng pí", "weasel skin / fur", "kulit musang / cerpelai"],
    ["的", "de", "particle", "punya"],
    ["，", "", "", ""],
    ["真", "zhēn", "really", "sungguh"],
    ["不容易", "bù róng yì", "not easy (precious)", "bukan mudah / amat berharga"],
    ["。”", "", "", ""], // 🎯 已完全修复合并
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["附信", "fù xìn", "attached a note", "melampirkan surat"],
    ["送来", "sòng lái", "sent over", "menyampaikan"],
    ["了", "le", "particle", ""],
    ["几句话", "jǐ jù huà", "a few words", "beberapa patah perkataan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["乡亲", "xiang qīn", "villagers", "orang kampung"],
    ["给的", "gěi de", "given by", "yang memberi"],
    ["，", "", "", ""],
    ["我想", "wǒ xiǎng", "I think", "saya fikir"],
    ["爹", "diē", "dad", "ayah"],
    ["年事已高", "nián shì yǐ gāo", "advanced in years / old age", "sudah lanjut usia"],
    ["，", "", "", ""],
    ["还是", "hái shì", "had better / still", "lebih baik / jugalah"],
    ["送给", "sòng gěi", "give to", "hadiahkan kepada"],
    ["爹", "diē", "dad", "ayah"],
    ["吧", "ba", "particle", ""],
    ["！”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 第 6 段

    ["爹", "diē", "dad", "Ayah"],
    ["把", "bǎ", "structural particle", ""],
    ["坎肩", "kǎn jiān", "vest", "ves bulu"],
    ["摸了又摸", "mō le yòu mō", "stroked again and again", "menyentuh berulang-ulang kali"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["寄回去", "jì huí qù", "mail it back", "hantar pos balik"],
    ["。”", "", "", ""], // 🎯 已完全修复合并
    ["我", "wǒ", "I", "Saya"],
    ["取出了", "qǔ chū le", "took out", "mengeluarkan"],
    ["纸笔", "zhǐ bǐ", "paper and pen", "kertas dan pen"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["捎带着", "shāo dài zhe", "incidentally / along with it", "sekali jalan / sambil-sambil itu"],
    ["写", "xiě", "write", "menulis"],
    ["封", "fēng", "measure word", "sepucuk"],
    ["信", "xìn", "letter", "surat"],
    ["吧", "ba", "particle", "kah"],
    ["？”", "", "", ""], // 🎯 已完全修复合并
    ["爹", "diē", "dad", "Ayah"],
    ["蹲在", "dūn zài", "squatting at", "mencangkung di"],
    ["大门口", "dà mén kǒu", "main gate", "pintu besar / pintu depan"],
    ["抽烟", "chōu yān", "smoking", "menghisap rokok"],
    ["，", "", "", ""],
    ["闷闷", "mèn mèn", "silently / heavily", "dengan senyap / berkepul-kepul"],
    ["一口", "yì kǒu", "a puff / mouthful", "sedutan"],
    ["，", "", "", ""],
    ["闷闷", "mèn mèn", "silently", "dengan senyap"],
    ["一口", "yì kǒu", "a puff", "sedutan"],
    ["，", "", "", ""],
    ["闷", "mēn", "brooded / spent silently", "termenung / meluangkan masa"],
    ["了", "le", "particle", ""],
    ["半宿", "bàn xiǔ", "half the night", "separuh malam"],
    ["，", "", "", ""],
    ["闷出", "mēn chū", "muttered out", "mengeluarkan patah kata"],
    ["一句", "yí jù", "a sentence", "sebaris ayat"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["勿", "wù", "do not", "jangan"],
    ["牵挂", "qiān guà", "worry / be anxious about", "bimbang / risau / ingat-ingatan"],
    ["。”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 第 7 段

    ["那件", "nà jiàn", "that piece of", "baju helai itu"],
    ["黄鼠狼皮", "huáng shǔ láng pí", "weasel skin", "kulit musang"],
    ["坎肩", "kǎn jiān", "vest", "ves"],
    ["后来", "hòu lái", "later", "kemudiannya"],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["卖了", "mài le", "sold it", "menjualnya"],
    ["，", "", "", ""],
    ["换来", "huàn lái", "exchanged for / got in return", "mendapat tukaran"],
    ["一点", "yì diǎn", "a little", "sedikit"],
    ["钱", "qián", "money", "wang"],
    ["，", "", "", ""],
    ["买了", "mǎi le", "bought", "membeli"],
    ["些", "xiē", "some", "beberapa / sedikit"],
    ["粉笔", "fěn bǐ", "chalk", "kapur tulis"],
    ["、", "", "", ""],
    ["教具", "jiào jù", "teaching aids", "alat bantu mengajar"],
    ["之类", "zhī lèi", "and the like / such as", "dan seumpamanya"],
    ["，", "", "", ""],
    ["信中", "xìn zhōng", "in the letter", "dalam surat"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["没有", "méi yǒu", "without / no", "tiada"],
    ["粉笔", "fěn bǐ", "chalk", "kapur tulis"],
    ["的", "de", "particle", "yang"],
    ["日子", "rì zi", "days", "hari / masa"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "pun / lalu"],
    ["用", "yòng", "use", "menggunakan"],
    ["抹布", "mā bù", "rag / cloth", "kain buruk / kain lap"],
    ["蘸了水", "zhàn le shuǐ", "dipped in water", "dicelup air"],
    ["写", "xiě", "write", "menulis"],
    ["，", "", "", ""],
    ["水一干", "shuǐ yì gān", "once the water dries", "sebaik sahaja air kering"],
    ["，", "", "", ""],
    ["字", "zì", "words / characters", "tulisan / perkataan"],
    ["就", "jiù", "then", "akan"],
    ["消失", "xiāo shī", "disappear", "hilang / lenyap"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["倒", "dào", "actually / contrary to expectation", "sebaliknya pula"],
    ["反而", "fǎn ér", "instead / on the contrary", "malahan / justru"],
    ["提高", "tí gāo", "improved / raised", "meningkatkan"],
    ["了", "le", "particle", ""],
    ["识字", "shí zì", "literacy / learning characters", "mengenal huruf"],
    ["的", "de", "particle", "punya"],
    ["速度", "sù dù", "speed", "kelajuan / kepantasan"],
    ["，", "", "", ""],
    ["全乡", "quán xiāng", "whole township", "seluruh kampung / mukim"],
    ["比赛", "bǐ sài", "competition", "pertandingan"],
    ["，", "", "", ""],
    ["夺了", "duó le", "won / took", "merangkul / memenangi"],
    ["头名", "tóu míng", "first place", "tempat pertama / juara"],
    ["！”", "", "", ""], // 🎯 已完全修复合并
    ["弟弟", "dì di", "younger brother", "Adik lelaki"],
    ["寄回", "jì huí", "sent back", "menghantar balik"],
    ["一张", "yì zhāng", "a (measure word for paper)", "sekeping"],
    ["奖状", "jiǎng zhuàng", "certificate of merit", "sijil penghargaan / elaun"],
    ["。", "", "", ""],
    ["爹", "diē", "dad", "Ayah"],
    ["看了又看", "kàn le yòu kàn", "looked at it again and again", "melihat berulang-ulang kali"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["贴上", "tiē shàng", "paste it up", "tampalkan"],
    ["，", "", "", ""],
    ["哪儿", "nǎ r", "wherever", "di mana yang"],
    ["显眼", "xiǎn yǎn", "conspicuous / eye-catching", "menonjol / ketara / senang dilihat"],
    ["贴", "tiē", "paste", "tampal"],
    ["哪儿", "nǎ r", "there", "di situ"],
    ["！”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 第 8 段

    ["没有", "méi yǒu", "no / lack of", "Tiada"],
    ["粉笔", "fěn bǐ", "chalk", "kapur tulis"],
    ["使用", "shǐ yòng", "use", "untuk digunakan"],
    ["的", "de", "particle", "punya"],
    ["事儿", "shì r", "matter / situation", "perkara"],
    ["吓了", "xià le", "frightened / shocked", "mengejutkan"],
    ["我", "wǒ", "me", "saya"],
    ["一大跳", "yí dà tiào", "a big start / jump", "amat sangat"],
    ["，", "", "", ""],
    ["小心翼翼", "xiǎo xīn yì yì", "cautiously / carefully", "dengan berhati-hati"],
    ["地", "de", "particle", ""],
    ["寄信", "jì xìn", "mail a letter", "menghantar surat"],
    ["去", "qù", "to", "untuk"],
    ["问", "wèn", "ask", "bertanya"],
    ["。", "", "", ""],
    ["弟弟", "dì di", "younger brother", "Adik lelaki"],
    ["回信", "huí xìn", "replied in a letter", "membalas surat"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["张艺谋", "zhāng yì móu", "Zhang Yimou (director)", "Zhang Yimou (pengarah filem)"],
    ["拍", "pāi", "filmed / directed", "merakam / mengarah"],
    ["的", "de", "particle", "yang"],
    ["《一个都不能少》", "yí gè dōu bù néng shǎo", "Not One Less (movie title)", "Not One Less (tajuk filem)"],
    ["，", "", "", ""],
    ["看过", "kàn guò", "have seen", "pernah tonton"],
    ["吧", "ba", "particle", "kan"],
    ["？", "", "", ""],
    ["人家", "rén jia", "other people / that", "orang itu / dia"],
    ["小魏老师", "xiǎo wèi lǎo shī", "Teacher Xiao Wei", "Cikgu Xiao Wei"],
    ["有一个", "yǒu yí gè", "has a", "mempunyai seorang"],
    ["学生", "xué sheng", "student", "murid"],
    ["跑去", "pǎo qù", "ran off to", "pergi lari"],
    ["打工", "dǎ gōng", "work part-time / labor", "bekerja buruh"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["去找", "qù zhǎo", "went to look for", "pergi mencari"],
    ["，", "", "", ""],
    ["最后", "zuì hòu", "finally", "akhirnya"],
    ["不仅", "bù jǐn", "not only", "bukan sahaja"],
    ["找回", "zhǎo huí", "found back", "menemui semula"],
    ["了", "le", "particle", ""],
    ["学生", "xué sheng", "student", "murid itu"],
    ["，", "", "", ""],
    ["还", "hái", "also", "malah turut"],
    ["找回", "zhǎo huí", "brought back", "mendapat balik"],
    ["了", "le", "particle", ""],
    ["一车", "yì chē", "a cartload of / a car of", "sekereta penuhan"],
    ["学习用具", "xué xí yòng jù", "learning stationeries / materials", "peralatan belajar"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["呢", "ne", "particle (what about me)", "pula"],
    ["？", "", "", ""],
    ["我的", "wǒ de", "my", "Saya punya"],
    ["学生", "xué sheng", "students", "murid-murid"],
    ["让", "ràng", "even if you let / ask", "kalau disuruh / biarkan"],
    ["他", "tā", "them", "mereka"],
    ["少", "shǎo", "be fewer / missing", "berkurangan / tercicir"],
    ["他", "tā", "they", "mereka"],
    ["都", "dōu", "even", "pun"],
    ["少不了", "shǎo bù liǎo", "cannot be fewer", "tidak boleh berkurangan"],
    ["！”", "", "", ""], // 🎯 已完全修复合并
    ["因为", "yīn wèi", "because", "Kerana"],
    ["，", "", "", ""],
    ["乡亲们", "xiāng qīn men", "the villagers", "orang-orang kampung"],
    ["就算", "jiù suàn", "even if", "walaupun / sekalipun"],
    ["累死", "lèi sǐ", "die of exhaustion", "mati keletihan"],
    ["饿死", "è sǐ", "starve to death", "mati kelaparan"],
    ["，", "", "", ""],
    ["也不会", "yě bú huì", "will also not", "tidak akan juga"],
    ["让", "ràng", "let / allow", "membiarkan"],
    ["儿女", "ér nǚ", "children", "anak-anak"],
    ["休学", "xiū xué", "drop out of school / suspend schooling", "berhenti sekolah / menangguhkan sekolah"],
    ["！”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 第 9 段

    ["再", "zài", "more / further", "Kemudian"],
    ["后来", "hòu lái", "later", "selepas itu"],
    ["的", "de", "particle", "punya"],
    ["来信", "lái xìn", "incoming letters", "surat kiriman"],
    ["，", "", "", ""],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["谈", "tán", "talk about", "bercerita tentang"],
    ["自己", "zì jǐ", "himself", "diri sendiri"],
    ["的", "de", "particle", "punya"],
    ["事情", "shì qing", "matters / things", "perkara"],
    ["少", "shǎo", "less", "semakin kurang"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["提", "tí", "mention", "menyebut / membangkitkan"],
    ["他的", "tā de", "his", "dia punya"],
    ["学生", "xué sheng", "students", "murid-murid"],
    ["渐渐", "jiàn jiàn", "gradually", "lambat-laun / semakin"],
    ["多", "duō", "more", "banyak"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["全是", "quán shì", "all are", "semuanya adalah"],
    ["些", "xiē", "some", "beberapa"],
    ["猫三狗四", "māo sān gǒu sì", "random / ordinary colloquial names", "nama-nama sebarangan / nama kampung"],
    ["的", "de", "particle", "yang"],
    ["名字", "míng zi", "names", "nama"],
    ["，", "", "", ""],
    ["谁谁谁", "shuí shuí shuí", "so-and-so", "si anu / sesiapa sahaja"],
    ["的", "de", "particle", "punya"],
    ["名次", "míng cì", "ranking", "kedudukan / ranking"],
    ["提前", "tí qián", "moved forward / improved", "meningkat maju / naik"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["谁谁谁", "shuí shuí shuí", "so-and-so", "si anu"],
    ["考了", "kǎo le", "scored in exam", "mendapat markah ujian"],
    ["满分", "mǎn fēn", "full marks", "markah penuh"],
    ["，", "", "", ""],
    ["谁谁谁", "shuí shuí shuí", "so-and-so", "si anu"],
    ["到", "dào", "go to", "pergi ke"],
    ["乡里", "xiāng lǐ", "township", "peringkat kampung"],
    ["、", "", "", ""],
    ["市里", "shì lǐ", "city", "peringkat bandar"],
    ["比赛", "bǐ sài", "compete", "bertanding"],
    ["等等", "děng děng", "etc / and so on", "dan sebagainya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["高声", "gāo shēng", "loudly", "dengan suara lantang"],
    ["读信", "dú xìn", "read the letter", "membaca surat"],
    ["，", "", "", ""],
    ["爹", "diē", "dad", "ayah"],
    ["在一旁", "zài yī páng", "by the side", "di tepi / di sebelah"],
    ["就", "jiù", "then", "pun"],
    ["直点头", "zhí diǎn tóu", "kept nodding", "asyik mengangguk-angguk"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["把", "bǎ", "structural particle", ""],
    ["信", "xìn", "letter", "surat"],
    ["读完了", "dú wán le", "finished reading", "habis membaca"],
    ["，", "", "", ""],
    ["爹", "diē", "dad", "ayah"],
    ["还在", "hái zài", "was still", "masih sedang"],
    ["点头", "diǎn tóu", "nodding", "mengangguk head"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不孬", "bù nāo", "not bad / excellent", "bukan kepalang / hebat / bagus"],
    ["，", "", "", ""],
    ["咱", "zán", "our", "kita punya"],
    ["于老三", "yú lǎo sān", "Yu Laosan (name)", "Yu Laosan (nama orang)"],
    ["的", "de", "of", "punya"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["，", "", "", ""],
    ["不孬", "bù nāo", "not bad / great", "hebat / bagus"],
    ["……”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 第 10 段

    ["过春节", "guò chūn jié", "celebrate Spring Festival", "menyambut Tahun Baru Cina"],
    ["的", "de", "particle", "yang"],
    ["时候", "shí hou", "time", "masa / ketika"],
    ["，", "", "", ""],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["回来", "huí lái", "come back", "pulang / balik"],
    ["。", "", "", ""],
    ["爹", "diē", "dad", "Ayah"],
    ["提了", "tí le", "carried / held", "memegang / menjinjing"],
    ["红灯笼", "hóng dēng long", "red lantern", "tanglung merah"],
    ["在", "zài", "at", "di"],
    ["村口", "cūn kǒu", "village entrance", "pintu masuk kampung"],
    ["站着", "zhàn zhe", "standing", "berdiri"],
    ["望了", "wàng le", "gazed / looked", "memandang"],
    ["半宿", "bàn xiǔ", "half the night", "separuh malam"],
    ["，", "", "", ""],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["还是", "hái shì", "still", "tetap / masih"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["回来", "huí lái", "come back", "pulang"],
    ["。", "", "", ""],
    ["年", "nián", "festival days / year", "hari raya / tahun baru"],
    ["还", "hái", "still", "masih"],
    ["没有", "méi yǒu", "not yet", "belum"],
    ["过完", "guò wán", "finished", "habis berlalu"],
    ["，", "", "", ""],
    ["爹", "diē", "dad", "ayah"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["按捺不住", "àn nà bú zhù", "could not contain himself", "tidak dapat menahan sabar lagi"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["闯关东", "chuǎng guān dōng", "braving the journey to Northeast China", "berpetualang ke daerah jauh / merantau jauh"],
    ["似的", "shì de", "as if / like", "seolah-olah"],
    ["周身", "zhōu shēn", "whole body", "seluruh badan"],
    ["挂满", "guà mǎn", "hung all over", "sarat digantung dengan"],
    ["物品", "wù pǐn", "goods / items", "barang-barangan"],
    ["找", "zhǎo", "look for", "mencari"],
    ["小儿子", "xiǎo ér zi", "youngest son", "anak bongsu"],
    ["去了", "qù le", "went", "pergi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["爹", "diē", "dad", "Ayah"],
    ["是", "shì", "was (emphasize)", "sememangnya"],
    ["哭着", "kū zhe", "crying", "sambil menangis"],
    ["回来", "huí lái", "came back", "pulang"],
    ["的", "de", "particle", ""],
    ["。", "", "", ""],
    ["爹", "diē", "dad", "Ayah"],
    ["泪汪汪", "lèi wāng wāng", "with tearful eyes", "dengan mata berlinang air mata"],
    ["地", "de", "particle", ""],
    ["望着", "wàng zhe", "gazed at", "memandang"],
    ["我", "wǒ", "me", "saya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "Kamu"],
    ["知道", "zhī dào", "know", "tahu"],
    ["吗", "ma", "particle (question)", "kah"],
    ["？", "", "", ""],
    ["你弟", "nǐ dì", "your brother", "adik kamu"],
    ["不回来", "bù huí lái", "not coming back", "tidak pulang"],
    ["，", "", "", ""],
    ["是", "shì", "is because", "adalah kerana"],
    ["舍不得", "shě bu de", "grudge spending / reluctant to part with", "sayang nak membazir / tidak sanggup mengeluarkan"],
    ["那", "nà", "that", "itu"],
    ["几十块钱", "jǐ shí kuài qián", "dozens of yuan", "beberapa puluh ringgit / yuan"],
    ["车票", "chē piào", "bus or train ticket", "tiket bas / kereta api"],
    ["意识", "yì shí", "consciousness", "kesedaran"],
    ["。", "", "", ""],
    ["你", "nǐ", "you", "Kamu"],
    ["知道", "zhī dào", "know", "tahu"],
    ["吗", "ma", "particle", "kah"],
    ["？”", "", "", ""], // 🎯 已完全修复合并
    ["爹", "diē", "dad", "Ayah"],
    ["说", "shuō", "said", "berkata"],
    ["他", "tā", "he", "dia"],
    ["像", "xiàng", "like", "seperti"],
    ["瞎子", "xiā zi", "blind man", "orang buta"],
    ["似的", "shì de", "as if", "seolah-olah"],
    ["在", "zài", "in", "di dalam"],
    ["山里", "shān lǐ", "mountains", "gunung / bukit"],
    ["转", "zhuàn", "wandering around / lost", "pusing-pusing / sesat"],
    ["，", "", "", ""],
    ["好不容易", "hǎo bù róng yì", "with great difficulty", "dengan amat sukar / susah payah"],
    ["逮着", "dǎi zháo", "caught sight of / met", "terserempak / menemui"],
    ["个人", "gè rén", "a person", "seorang manusia"],
    ["，", "", "", ""],
    ["上前", "shàng qián", "stepped forward", "melangkah ke hadapan"],
    ["说", "shuō", "said", "dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["兄弟", "xiōng di", "brother / mister", "saudara / encik"],
    ["，", "", "", ""],
    ["问个路", "wèn gè lù", "ask for directions", "tumpang tanya jalan"],
    ["。”", "", "", ""], // 🎯 已完全修复合并
    ["那人", "nà rén", "that person", "orang itu"],
    ["一回头", "yì huí tóu", "turned around", "sebaik memalingkan muka"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["啊呀", "ā yā", "oh my gosh", "alboi / rupa-rupanya"],
    ["——", "", "", ""],
    ["是", "shì", "is", "adalah"],
    ["爹", "diē", "dad", "ayah"],
    ["！", "”", "", ""],
    ["这以后", "zhè yǐ hòu", "since then", "sejak itu"],
    ["，", "", "", ""],
    ["爹", "diē", "dad", "ayah"],
    ["一直", "yì zhí", "kept / always", "sentiasa"],
    ["闷着气", "mèn zhe qì", "sulking / keeping quiet moodily", "memendam rasa / berdiam diri"],
    ["。", "", "", ""],
    ["问", "wèn", "asked", "Apabila ditanya"],
    ["他", "tā", "him", "dia"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["就", "jiù", "then", "pun"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["不是", "bú shì", "is not", "bukan"],
    ["人", "rén", "human", "manusia"],
    ["待", "dāi", "stay", "tinggal"],
    ["的", "de", "particle", "yang"],
    ["地方", "dì fang", "place", "tempat"],
    ["！”", "", "", ""], // 🎯 已完全修复合并
    ["爹", "diē", "dad", "Ayah"],
    ["让我", "ràng wǒ", "asked me to", "menyuruh saya"],
    ["写信", "xiě xìn", "write a letter", "menulis surat"],
    ["把", "bǎ", "structural particle", ""],
    ["弟弟", "dì di", "younger brother", "adik lelaki"],
    ["叫回来", "jiào huí lái", "call back", "panggil balik"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不用", "bú yòng", "no need to", "tidak usah"],
    ["教书", "jiāo shū", "teach", "mengajar lagi"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["跟", "gēn", "with", "ikut"],
    ["爹", "diē", "dad", "ayah"],
    ["在", "zài", "in", "di dalam"],
    ["大棚", "dà péng", "greenhouse", "rumah hijau"],
    ["里", "lǐ", "inside", "dalam"],
    ["种", "zhòng", "plant / grow", "menanam"],
    ["反季节菜", "fǎn jì jié cài", "off-season vegetables", "sayur-sayuran luar musim"],
    ["，", "", "", ""],
    ["挣钱", "zhèng qián", "earn money", "cari duit"],
    ["！”", "", "", ""], // 🎯 已完全修复合并
    ["弟弟", "dì di", "younger brother", "Adik lelaki"],
    ["很快", "hěn kuài", "very quickly", "dengan sangat cepat"],
    ["就", "jiù", "then", "pun"],
    ["回信", "huí xìn", "replied", "membalas surat"],
    ["了", "le", "particle", ""],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["决定了", "jué dìng le", "decided", "sudah buat keputusan"],
    ["，", "", "", ""],
    ["不回去", "bù huí qù", "not going back", "tidak akan balik"],
    ["！”", "", "", ""], // 🎯 已完全修复合并
    ["弟弟", "dì di", "younger brother", "Adik lelaki"],
    ["还在", "hái zài", "also in", "juga dalam"],
    ["信中", "xìn zhōng", "in the letter", "surat itu"],
    ["说", "shuō", "said", "berkata"],
    ["春天", "chūn tiān", "spring", "musim bunga"],
    ["到了", "dào le", "has arrived", "telah tiba"],
    ["，", "", "", ""],
    ["许多", "xǔ duō", "many", "banyak"],
    ["花儿", "huā r", "flowers", "bunga-bungaan"],
    ["都", "dōu", "all", "semuanya"],
    ["开了", "kāi le", "bloomed", "telah mekar"],
    ["，", "", "", ""],
    ["学生们", "xué sheng men", "students", "murid-murid"],
    ["上山", "shàng shān", "go up the mountain", "pergi ke bukit"],
    ["采花", "cǎi huā", "pick flowers", "memetik bunga"],
    ["，", "", "", ""],
    ["不是", "bú shì", "not", "bukan"],
    ["掐断", "qiā duàn", "pluck / snap off", "mematahkan / memetik"],
    ["，", "", "", ""],
    ["而是", "ér shì", "but rather", "tetapi"],
    ["连泥", "lián ní", "with the soil / mud", "sekali dengan tanah / lumpur"],
    ["挖回", "wā huí", "dig out and bring back", "gali bawa balik"],
    ["，", "", "", ""],
    ["种在", "zhòng zài", "planted at", "ditanam di"],
    ["教室", "jiào shì", "classroom", "bilik darjah"],
    ["外", "wài", "outside", "luar / luar bangunan"],
    ["，", "", "", ""],
    ["有", "yǒu", "there are", "ada"],
    ["许多", "xǔ duō", "many", "banyak"],
    ["蜂儿", "fēng r", "bees", "lebah-lebah"],
    ["来", "lái", "come to", "datang"],
    ["舞", "wǔ", "dance / buzz around", "menari / terbang berkeliaran"],
    ["，", "", "", ""],
    ["很", "hěn", "very", "sangat"],
    ["美丽", "měi lì", "beautiful", "indah / cantik"],
    ["……”", "", "", ""], // 🎯 已完全修复合并

    ["\n", "", "", ""], // 👈 分段标记，切入文末作者出处

    // 🎯 独立出来的文末作者出处
    ["（", "", "", ""],
    ["于心亮", "yú xīn liàng", "Yu Xinliang (Author)", "Yu Xinliang (Penulis)"],
    ["《", "", "", ""],
    ["弟弟的来信", "dì di de lái xìn", "My Brother's Letter", "Surat Kiriman Adik Laki-laki"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with / has", "ada"],
    ["改动", "gǎi dòng", "adaptations / modifications", "perubahan / ubah suai"],
    ["）", "", "", ""]
];
// =====================================================================
